-- Additive Phase 1 two-stage strategy, signal, replay, and owner-review evidence.
create table if not exists public.strategies (
  id bigint generated by default as identity primary key,
  strategy_code text not null, version integer not null check (version > 0),
  config_hash text not null, config jsonb not null, status text not null default 'draft'
    check (status in ('draft','backtested','approved','retired')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (strategy_code, version, config_hash)
);

create table if not exists public.strategy_setups (
  id bigint generated by default as identity primary key,
  strategy_code text not null, strategy_version integer not null, config_hash text not null,
  symbol text not null, setup_date date not null, target_session date not null,
  status text not null check (status in ('passed','failed','not_evaluable')), decision jsonb not null,
  created_at timestamptz not null default now(),
  unique (strategy_code, strategy_version, config_hash, symbol, setup_date, target_session)
);

create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  strategy_code text not null, strategy_version integer not null, config_hash text not null,
  symbol text not null, setup_date date not null, scan_slot text not null, signal_time timestamptz not null,
  decision jsonb not null, created_at timestamptz not null default now(),
  unique (strategy_code, strategy_version, config_hash, symbol, setup_date, scan_slot, signal_time)
);

create table if not exists public.backtest_runs (
  id uuid primary key default gen_random_uuid(), strategy_code text not null,
  strategy_version integer not null, config_hash text not null,
  idempotency_key text not null unique, mode text not null check (mode in ('daily_intraday','daily_only')),
  scope jsonb not null, assumptions jsonb not null, data_quality jsonb not null,
  status text not null check (status in ('running','completed','failed')),
  metrics jsonb, created_at timestamptz not null default now(), completed_at timestamptz
);

create table if not exists public.backtest_signals (
  id bigint generated by default as identity primary key, backtest_run_id uuid not null references public.backtest_runs(id) on delete cascade,
  strategy_code text not null, strategy_version integer not null, config_hash text not null,
  symbol text not null, setup_date date not null, scan_slot text not null, signal_time timestamptz not null,
  entry_session date not null, entry_status text not null, entry_time timestamptz, entry_price double precision,
  h1_status text not null, h1_session date, h1_close double precision, h1_gross_return double precision,
  h3_status text not null, h3_session date, h3_close double precision, h3_gross_return double precision,
  h5_status text not null, h5_session date, h5_close double precision, h5_gross_return double precision,
  decision jsonb not null, created_at timestamptz not null default now(),
  unique (backtest_run_id, strategy_code, strategy_version, config_hash, symbol, setup_date, scan_slot, signal_time)
);

create table if not exists public.strategy_reviews (
  id bigint generated by default as identity primary key,
  strategy_code text not null, strategy_version integer not null, config_hash text not null,
  backtest_run_id uuid not null references public.backtest_runs(id),
  decision text not null check (decision in ('approve','reject')), owner text not null, notes text not null,
  reviewed_at timestamptz not null default now(),
  unique (strategy_code, strategy_version, config_hash, backtest_run_id)
);

create index if not exists strategy_setups_target_idx on public.strategy_setups(target_session, symbol);
create index if not exists signals_time_idx on public.signals(signal_time, symbol);
create index if not exists backtest_signals_run_idx on public.backtest_signals(backtest_run_id);

-- Verification (expect six rows and no legacy table rows):
-- select table_name from information_schema.tables where table_schema='public'
--   and table_name in ('strategies','strategy_setups','signals','backtest_runs','backtest_signals','strategy_reviews') order by table_name;
-- select table_name from information_schema.tables where table_schema='public'
--   and table_name in ('trading_signals','backtest_data');
-- select indexname, indexdef from pg_indexes where schemaname='public'
--   and tablename in ('strategies','strategy_setups','signals','backtest_runs','backtest_signals','strategy_reviews');

-- Rollback guidance: stop strategy/signal/backtest writers, export review evidence,
-- then drop the six new tables in reverse dependency order. Raw, clean, and
-- features are untouched; rollback deletes only newly generated Phase 1 evidence.
