create table if not exists stream_raw_snapshot (
    id bigserial primary key,
    channel text not null,
    rtype text,
    symbol text,
    index_code text,
    time timestamptz not null,
    trading_date date,
    payload jsonb not null,
    created_at timestamptz default now()
);
create unique index if not exists ux_stream_raw_snapshot_channel_time on stream_raw_snapshot(channel, time);

create table if not exists stream_quote_snapshot (
    symbol text not null,
    time timestamptz not null,
    trading_date date,
    exchange text,
    market_id text,
    trading_session text,
    trading_status text,
    ceiling double precision,
    floor double precision,
    ref_price double precision,
    open double precision,
    close double precision,
    high double precision,
    low double precision,
    avg_price double precision,
    last_price double precision,
    last_vol bigint,
    total_vol bigint,
    total_val bigint,
    change double precision,
    ratio_change double precision,
    est_matched_price double precision,
    bid_price_1 double precision, bid_vol_1 bigint, ask_price_1 double precision, ask_vol_1 bigint,
    bid_price_2 double precision, bid_vol_2 bigint, ask_price_2 double precision, ask_vol_2 bigint,
    bid_price_3 double precision, bid_vol_3 bigint, ask_price_3 double precision, ask_vol_3 bigint,
    bid_price_4 double precision, bid_vol_4 bigint, ask_price_4 double precision, ask_vol_4 bigint,
    bid_price_5 double precision, bid_vol_5 bigint, ask_price_5 double precision, ask_vol_5 bigint,
    bid_price_6 double precision, bid_vol_6 bigint, ask_price_6 double precision, ask_vol_6 bigint,
    bid_price_7 double precision, bid_vol_7 bigint, ask_price_7 double precision, ask_vol_7 bigint,
    bid_price_8 double precision, bid_vol_8 bigint, ask_price_8 double precision, ask_vol_8 bigint,
    bid_price_9 double precision, bid_vol_9 bigint, ask_price_9 double precision, ask_vol_9 bigint,
    bid_price_10 double precision, bid_vol_10 bigint, ask_price_10 double precision, ask_vol_10 bigint,
    total_bid_depth_10 bigint,
    total_ask_depth_10 bigint,
    orderbook_imbalance double precision,
    pressure_score double precision,
    raw jsonb,
    created_at timestamptz default now()
);
create unique index if not exists ux_stream_quote_snapshot_symbol_time on stream_quote_snapshot(symbol, time);

create table if not exists stream_trade_snapshot (
    symbol text not null,
    time timestamptz not null,
    trading_date date,
    exchange text,
    market_id text,
    trading_session text,
    trading_status text,
    ceiling double precision,
    floor double precision,
    ref_price double precision,
    open double precision,
    close double precision,
    high double precision,
    low double precision,
    avg_price double precision,
    last_price double precision,
    last_vol bigint,
    total_vol bigint,
    total_val bigint,
    change double precision,
    ratio_change double precision,
    est_matched_price double precision,
    raw jsonb,
    created_at timestamptz default now()
);
create unique index if not exists ux_stream_trade_snapshot_symbol_time on stream_trade_snapshot(symbol, time);

create table if not exists stream_foreign_snapshot (
    symbol text not null,
    time timestamptz not null,
    trading_date date,
    exchange text,
    market_id text,
    total_room bigint,
    current_room bigint,
    foreign_buy_vol bigint,
    foreign_sell_vol bigint,
    foreign_buy_val bigint,
    foreign_sell_val bigint,
    net_foreign_vol bigint,
    net_foreign_val bigint,
    raw jsonb,
    created_at timestamptz default now()
);
create unique index if not exists ux_stream_foreign_snapshot_symbol_time on stream_foreign_snapshot(symbol, time);

create table if not exists stream_index_snapshot (
    index_code text not null,
    time timestamptz not null,
    trading_date date,
    exchange text,
    market text,
    index_value double precision,
    index_val_est double precision,
    prior_index_value double precision,
    change double precision,
    ratio_change double precision,
    total_trade bigint,
    total_qtty bigint,
    total_value bigint,
    total_qtty_pt bigint,
    total_value_pt bigint,
    total_qtty_od bigint,
    total_value_od bigint,
    all_qty bigint,
    all_value bigint,
    advances integer,
    no_changes integer,
    declines integer,
    ceilings integer,
    floors integer,
    index_type text,
    index_name text,
    trading_session text,
    raw jsonb,
    created_at timestamptz default now()
);
create unique index if not exists ux_stream_index_snapshot_index_code_time on stream_index_snapshot(index_code, time);
