name: Run Python Daily

on:
  schedule:
    # 7h sáng VN mỗi ngày
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
      SUPABASE_SERVICE_KEY: ${{secrets.SUPABASE_SERVICE_KEY}}
      SSI_CONSUMER_ID: ${{secrets.SSI_CONSUMER_ID}}
      SSI_CONSUMER_SECRET: ${{secrets.SSI_CONSUMER_SECRET}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py daily
        run: python main.py daily
